version: '3.9'

services:
  master-cluster:
    build: .  # Costruisce l'immagine usando il Dockerfile
    container_name: master-cluster
    hostname: master-cluster
    networks:
      - redis-cluster-network
    ports:
      - "6379:6379"  # Espone la porta 6379
    volumes:
      - ./data/master:/data  # Bind mount per il master
      - redis-master-data:/data/redis  # Volume Docker per i dati di Redis
    restart: always

  slave_1:
    build: .  # Costruisce l'immagine usando il Dockerfile
    container_name: slave_1
    hostname: slave_1
    networks:
      - redis-cluster-network
    volumes:
      - ./data/slave_1:/data  # Bind mount per slave 1
      - redis-slave1-data:/data/redis  # Volume Docker per i dati di Redis
    restart: always

  slave_2:
    build: .  # Costruisce l'immagine usando il Dockerfile
    container_name: slave_2
    hostname: slave_2
    networks:
      - redis-cluster-network
    volumes:
      - ./data/slave_2:/data  # Bind mount per slave 2
      - redis-slave2-data:/data/redis  # Volume Docker per i dati di Redis
    restart: always

networks:
  redis-cluster-network:
    driver: bridge

volumes:
  redis-master-data:  # Volume per il master
  redis-slave1-data:  # Volume per slave 1
  redis-slave2-data:  # Volume per slave 2
